# Generated by Django 4.1.1 on 2022-10-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_box',
            old_name='key',
            new_name='fkey',
        ),
        migrations.AlterField(
            model_name='comment_box',
            name='msg',
            field=models.TextField(),
        ),
    ]
